version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: attendance-postgres
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: attendance-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres